---
title: "Assessing Top Soccer Player Statistics"
subtitle: "Preregistration of analyses"
format: html
editor: visual
execute:
  echo: true
---

RQ 1 (Players): Is there a correlation between the height, weight, age, and/or player rating on specific game statistics (Including, but not limited to: goals scored, assists, penalties, passes, etc.)?

-   Do taller players (player_height) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do heavier players (player_weight) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do older players (player_birth_date) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do higher rated players (player_birth_date) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do taller players (player_height) tend to score more (goals_total)?

-   Do heavier players (player_weight) tend to score more (goals_total)?

-   Do older players (player_birth_date) tend to score more (goals_total)?

-   Do higher rated players (player_birth_date) tend to score more (goals_total)?

-   Do taller players (player_height) tend to have higher goal accuracy (mutate --\> goal_acc = goals_total / shots_total)?

-   Do heavier players (player_weight) tend to have higher goal accuracy (mutate --\> goal_acc = goals_total / shots_total)?

-   Do older players (player_birth_date) tend to have higher goal accuracy (mutate --\> goal_acc = goals_total / shots_total)?

-   Do higher rated players (player_birth_date) tend to have higher goal accuracy (mutate --\> goal_acc = goals_total / shots_total)?

RQ 2 (Leagues): Do game statistics differ across leagues (goals_total)?

-   Are some leagues (leagues) outputting more goals than others?

-   Does penalty accuracy rate vary across leagues? (i.e. mutate -\> penalty_acc = penalty_scored / (penalty_missed + penalty_scored))

-   How does the frequency of fouls (cards_yellow, cards_red, cards_redyellow) between different leagues, impact the number of goals scored?

-   How do goals per minutes (on average) (i.e. goals_total / games_minutes and group_by(league)) differ within leagues?

-   Does number of duels (duels_total) differ across leagues?

# Analysis #1

Question: What factors influence booking frequency of the players?

Hypothesis: Taller, heavier, older, and more highly rated players get booked more frequently than shorter, less heavy, younger, less highly rated players.

-   Do taller players (player_height) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do heavier players (player_weight) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do older players (player_birth_date) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

-   Do higher rated players (player_birth_date) tend to get booked more frequently (mutate --\> total_bookings = cards_yellow + cards_red + cards_redyellow)?

# Analysis #2

Question: Are some leagues more aggressive, on average, than others?

Hypothesis: European leagues are, on average, more aggressive than non-European leagues (i.e. more fouls, more goals per minute, and more duels.)

-   How does the frequency of bookings (cards_yellow, cards_red, cards_redyellow) between different leagues, impact the average goals per match? Does this differ across European and non European leagues?

-   How does the frequency of penalties differ between different leagues?

-   Does the number of straight red cards versus second yellow cards per game differ across leagues?

-   How do goals per minutes (on average) (i.e. goals_total / games_minutes and group_by(league)) differ within leagues?

-   Do the average amount of shots per game differ across leagues?

-   Does number of duels (duels_total) differ across leagues?
